version: 0.1.0-{branch}-{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
init:
  - dotnet --version
build_script:
  - ps: .\build\build.ps1
test_script:
  - ps: .\build\test.ps1